### ISSUE TITLE
[bug]  fail to switch plugin

### ISSUE THREAD

**Issue by juestchaos** [ocapraro/obsidian-math-plus#11]
I had a console log when I switch plugin;

Plugin failure: obsidian-math-plus TypeError: Object.defineProperties called on non-object
    at Function.defineProperties (<anonymous>)
    at eval (App.tsx?0070:5586:10)
    at ../../components/App.tsx (excalidraw.development.js:1826:1)
    at __webpack_require__ (excalidraw.development.js:3192:42)
    at eval (index.tsx:31:73)
    at ./index.tsx (excalidraw.development.js:2794:1)
    at __webpack_require__ (excalidraw.development.js:3192:42)
    at eval (entry.js:26:64)
    at ./entry.js (excalidraw.development.js:2783:1)
    at __webpack_require__ (excalidraw.development.js:3192:42)

**Comment by ocapraro** [comment]
Could you go into more detail as to what exactly caused this, what do you mean by switch plugin?

**Comment by ocapraro** [comment]
Stale
